FROM php:8.4-cli

COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer

RUN curl -1sLf https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh | bash \
 && apt-get install -y symfony-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip

COPY php.ini /usr/local/etc/php/php.ini

WORKDIR /app
