FROM php:8.4-cli

COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer

RUN curl -1sLf https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh | bash \
 && apt-get install -y symfony-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY docker/php/php.ini /usr/local/etc/php/php.ini

WORKDIR /app

COPY symfony/composer.json symfony/composer.lock ./
RUN composer install --no-interaction --no-scripts
